#!/system/bin/sh

useragent="Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3"
download(){
# $1 = url
# $2 = local path
# lets see that curl exits successfully
until /system/bin/curl -s -k -L -A "$useragent" -o "$2" "$1" ;do
 sleep 25
done
}

initfile="/system/etc/init.d/32mad"

if ! [[ -f "$initfile" ]] ;then
 mkdir -p /data/local/madromlogs/
 mount -o remount,rw /system
 download https://raw.githubusercontent.com/ColdShadow80/MAD-ATV-DD/main/init.d/32mad "$initfile" && chmod +x /system/etc/init.d/*
 sleep 5
 if [[ -f /data/local/madromlogs/32mad.log ]] ;then
  rm -f -- /data/local/madromlogs/32mad.log.old
  mv /data/local/madromlogs/32mad.log /data/local/madromlogs/32mad.log.old
  /system/bin/sh -x "$initfile" 2>"/data/local/madromlogs/32mad.log"
 else
  /system/bin/sh -x "$initfile" 2>"/data/local/madromlogs/32mad.log"
 fi
fi
