#!/system/bin/sh

useragent="Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3"
download(){
# $1 = url
# $2 = local path
# lets see that curl exits successfully
until /system/bin/curl -s -k -L -A "$useragent" -o "$2" "$1" ;do
 sleep 25
done
}

case "$(uname -m)" in
 aarch64) MADboot="42mad";;
 armv8l)  MADboot="32mad";;
esac

if [[ -f /data/local/madromlogs/$MADboot.log ]] ;then
  rm -f -- /data/local/madromlogs/*.log.old
  for f in /data/local/madromlogs/*.log; do 
    mv -- "$f" "${f%.log}.log.old"
  done
fi

initfile="/system/etc/init.d/$MADboot"

if ! [[ -f "$initfile" ]] ;then
 mkdir -p /data/local/madromlogs/
 mount -o remount,rw /system
 # check if USB is mounted and autoconfig file is present each 5 seconds, up to 30s
 count=15
 i=0
 while [[ $i -lt $count && -z "$usbfile" ]]; do
  let i++
  sleep 2
 done
 CustomRom="$(find /mnt/media_rw/ -iname CustomRom.txt 2>/dev/null)"
 CustomUrl="$(awk 'NR==1{print $1}' "$CustomRom")"
 if [[ "$CustomUrl" ]] ;then
   download "$CustomUrl" "$initfile" && chmod +x /system/etc/init.d/*
   echo "Installing $MADboot from custom url"
 else
  download https://raw.githubusercontent.com/ColdShadow80/MAD-ATV-DD/develop/init.d/$MADboot "$initfile" && chmod +x /system/etc/init.d/*
  echo "Installing $MADboot from Main branch"
 fi
fi
 sleep 2
 /system/bin/sh -x "$initfile" 2>"/data/local/madromlogs/$MADboot.log"
fi
